; This files serves as memory map for how the game uses the 20 available sprite slots and the 20 available display lists


;-------------
; Sprite slots
;-------------

; 0 : slot 0 is always reserved for the player
; 1 :
; 2 :
; 3 :
; 4 :
; 5 :
; 6 :
; 7 :
; 8 :
; 9 :
; 10 :
; 11 :
; 12 :
; 13 :
; 14 :
; 15 :
; 16 :
; 17 :
; 18 :
; 19 :



;--------------
; Display list
;--------------

; 0 : Player display list addr (modified by player routines)
; 1 :
; 2 : Rolling ennemy display list, shared by all ennemies (modified by ennemies routine) 
; 3 :
; 4 :
; 5 :
; 6 :
; 7 :
; 8 :
; 9 :
; 10 :
; 11 :
; 12 :
; 13 :
; 14 :
; 15 :
; 16 :
; 17 :
; 18 :
; 19 :



